id: QmVH665JUWcCnt6jfPYg7cUNP4q8zG1qvWkXbHkEK7qqp6
description: Returns pong to a ping over http
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
